In [1]:
import numpy as np 
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf 
from tensorflow import keras
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy
# ressource below 
# ressources for confusion matrix 
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt
# https://www.youtube.com/watch?v=qFJeN9V1ZsI

2022-08-30 21:41:49.951549: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-30 21:41:49.951590: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
train_labels = [] 
train_samples = []

In [3]:
for i in range (50):
    # the 5% of younder individuals with side effects
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    # 5% of older participants with no side effects
    random_older = randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(0)
    
for i in range (1000):
    # 95% of younder with no side effects
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)
    # 95% of older with side effects
    random_older = randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(1)

In [4]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels, train_samples = shuffle(train_labels, train_samples)

In [5]:
# normalizing or standarizing data
scaler = MinMaxScaler(feature_range=(0,1))
# rescalling data to be between 0 and 1
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1, 1))

In [6]:
for i in scaled_train_samples:
    print (i)

[0.70114943]
[0.85057471]
[0.52873563]
[0.28735632]
[0.11494253]
[0.55172414]
[0.52873563]
[0.42528736]
[0.56321839]
[0.02298851]
[0.12643678]
[0.59770115]
[0.65517241]
[0.44827586]
[0.10344828]
[0.43678161]
[0.89655172]
[0.66666667]
[0.96551724]
[0.66666667]
[0.17241379]
[0.44827586]
[0.97701149]
[0.70114943]
[0.88505747]
[1.]
[1.]
[0.8045977]
[0.48275862]
[0.08045977]
[0.40229885]
[0.04597701]
[0.02298851]
[0.86206897]
[0.17241379]
[0.42528736]
[0.29885057]
[0.2183908]
[0.42528736]
[0.6091954]
[1.]
[0.71264368]
[0.17241379]
[0.20689655]
[0.05747126]
[0.43678161]
[0.32183908]
[0.24137931]
[0.13793103]
[0.81609195]
[0.14942529]
[0.87356322]
[0.62068966]
[0.96551724]
[0.62068966]
[0.45977011]
[0.27586207]
[0.75862069]
[0.68965517]
[0.08045977]
[0.27586207]
[0.13793103]
[0.86206897]
[0.91954023]
[0.47126437]
[0.94252874]
[0.11494253]
[0.98850575]
[0.87356322]
[0.74712644]
[0.36781609]
[0.08045977]
[0.73563218]
[0.87356322]
[0.52873563]
[0.67816092]
[0.63218391]
[0.75862069]
[0.68965517]


[0.79310345]
[0.47126437]
[0.56321839]
[0.65517241]
[0.67816092]
[0.10344828]
[0.43678161]
[0.47126437]
[0.09195402]
[0.89655172]
[0.86206897]
[0.85057471]
[0.88505747]
[0.65517241]
[0.66666667]
[0.66666667]
[0.8045977]
[0.63218391]
[0.13793103]
[0.48275862]
[0.74712644]
[0.57471264]
[0.24137931]
[0.35632184]
[0.97701149]
[0.45977011]
[0.85057471]
[0.06896552]
[0.29885057]
[0.28735632]
[0.6091954]
[0.62068966]
[0.74712644]
[0.89655172]
[1.]
[0.24137931]
[0.66666667]
[0.77011494]
[0.70114943]
[0.82758621]
[0.04597701]
[0.13793103]
[0.06896552]
[0.81609195]
[0.37931034]
[0.18390805]
[0.37931034]
[0.90804598]
[0.87356322]
[0.17241379]
[0.70114943]
[0.72413793]
[0.73563218]
[0.1954023]
[0.45977011]
[0.95402299]
[0.93103448]
[1.]
[0.14942529]
[0.24137931]
[0.11494253]
[0.96551724]
[0.64367816]
[0.04597701]
[0.35632184]
[0.57471264]
[0.50574713]
[0.35632184]
[0.85057471]
[0.02298851]
[0.55172414]
[0.82758621]
[0.20689655]
[0.11494253]
[0.17241379]
[0.]
[0.95402299]
[0.42528736]
[0.8045977]
[

[0.73563218]
[0.72413793]
[0.82758621]
[0.83908046]
[0.75862069]
[0.51724138]
[0.83908046]
[0.81609195]
[0.45977011]
[0.45977011]
[0.86206897]
[0.4137931]
[0.35632184]
[0.49425287]
[0.05747126]
[0.3908046]
[0.8045977]
[0.63218391]
[0.89655172]
[0.86206897]
[0.89655172]
[0.01149425]
[0.25287356]
[0.05747126]
[0.94252874]
[0.93103448]
[0.34482759]
[0.43678161]
[0.52873563]
[0.65517241]
[0.34482759]
[0.11494253]
[0.70114943]
[0.6091954]
[0.86206897]
[0.57471264]
[0.01149425]
[0.72413793]
[0.94252874]
[0.64367816]
[0.57471264]
[0.87356322]
[0.94252874]
[0.91954023]
[0.4137931]
[0.56321839]
[0.89655172]
[0.65517241]
[0.50574713]
[0.51724138]
[0.57471264]
[0.93103448]
[0.01149425]
[0.55172414]
[0.20689655]
[0.59770115]
[0.93103448]
[0.96551724]
[0.4137931]
[0.17241379]
[0.05747126]
[0.17241379]
[0.73563218]
[0.6091954]
[0.43678161]
[0.70114943]
[0.90804598]
[0.64367816]
[0.44827586]
[0.16091954]
[0.73563218]
[0.13793103]
[0.79310345]
[0.18390805]
[0.74712644]
[0.13793103]
[0.43678161]
[0.298

In [7]:
physical_devices = tf.config.experimental.list_physical_devices('GPU')
print ("GPUs:", len(physical_devices))


GPUs: 0


2022-08-30 21:41:54.440389: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-30 21:41:54.441356: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-30 21:41:54.441476: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-08-30 21:41:54.441581: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-08-30 21:41:54.441688: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In [8]:
model= Sequential([
    Dense(units=16, input_shape=(1,), activation='relu'),
    Dense(units=32, activation='relu'), # units is number of neurons
    Dense(units=2, activation='softmax')
])

2022-08-30 21:41:54.473798: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=["accuracy"])

In [11]:
model.fit(x=scaled_train_samples, 
          y=train_labels, 
          batch_size=10, 
          epochs=30, 
          shuffle=True, # on by default 
          validation_split=0.1, # 10% of data put aside for validation
          verbose=2)

Epoch 1/30
189/189 - 2s - loss: 0.6799 - accuracy: 0.5444 - val_loss: 0.6733 - val_accuracy: 0.5571 - 2s/epoch - 8ms/step
Epoch 2/30
189/189 - 1s - loss: 0.6607 - accuracy: 0.6063 - val_loss: 0.6551 - val_accuracy: 0.5952 - 699ms/epoch - 4ms/step
Epoch 3/30
189/189 - 1s - loss: 0.6370 - accuracy: 0.6788 - val_loss: 0.6293 - val_accuracy: 0.6762 - 526ms/epoch - 3ms/step
Epoch 4/30
189/189 - 1s - loss: 0.6098 - accuracy: 0.7312 - val_loss: 0.6042 - val_accuracy: 0.7143 - 523ms/epoch - 3ms/step
Epoch 5/30
189/189 - 1s - loss: 0.5830 - accuracy: 0.7608 - val_loss: 0.5789 - val_accuracy: 0.7571 - 584ms/epoch - 3ms/step
Epoch 6/30
189/189 - 1s - loss: 0.5561 - accuracy: 0.7725 - val_loss: 0.5521 - val_accuracy: 0.8048 - 572ms/epoch - 3ms/step
Epoch 7/30
189/189 - 1s - loss: 0.5285 - accuracy: 0.7963 - val_loss: 0.5252 - val_accuracy: 0.8143 - 509ms/epoch - 3ms/step
Epoch 8/30
189/189 - 1s - loss: 0.5008 - accuracy: 0.8037 - val_loss: 0.4965 - val_accuracy: 0.8238 - 517ms/epoch - 3ms/step
Epo

In [12]:
# overfitting is when it's very good at recognising the
# models it has been trained on but not good with new dat


In [13]:
predictions = model.predict(x=scaled_train_samples, batch_size=10, verbose=0)

In [17]:
rounded_predictions = np.argmax(predictions, axis=-1)

In [19]:
cm = confusion_matrix(
    y_true=train_labels,
    y_pred=rounded_predictions
)
cm

array([[ 967,   83],
       [  48, 1002]])

In [ ]:
# loading and saving models 

In [21]:
model.save('models/trial_model.h5')
# saves architecture of model
# the weights
# training configuration (loss, optimizer)
# optimization 

In [22]:
from tensorflow.keras.models import load_model
new_model = load_model('models/trial_model.h5')

In [23]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [24]:
new_model.get_weights()

[array([[-0.13111988, -0.49405888,  0.32288212,  0.6908481 ,  0.3815026 ,
         -0.0867557 , -0.47024238, -0.47138062,  0.36990273,  0.34954482,
         -0.13585597, -0.3409375 ,  0.58267593, -0.40695417,  0.1242618 ,
         -0.10593599]], dtype=float32),
 array([ 0.        ,  0.        , -0.10182349, -0.13192666, -0.11845144,
         0.1932446 ,  0.        ,  0.        , -0.11627998, -0.09120799,
         0.        ,  0.        , -0.08928965,  0.        ,  0.2537951 ,
         0.        ], dtype=float32),
 array([[ 3.00862521e-01,  1.27895713e-01, -2.34226733e-01,
         -2.66942531e-01,  3.11934203e-01,  1.06739759e-01,
         -3.14821005e-02, -1.91812918e-01,  2.97999710e-01,
          2.68792719e-01, -2.40195811e-01,  1.98442131e-01,
         -2.24444270e-01,  2.60453194e-01,  4.62585688e-03,
         -5.72068393e-02,  3.29906732e-01,  1.13468081e-01,
          2.98517644e-02, -2.96088099e-01,  2.19746679e-01,
         -1.14567354e-01, -2.99034238e-01,  2.22897679e-01,
 

In [25]:
new_model.optimizer

In [27]:
# saving model to json if we only want to save architecure
json_string = model.to_json()
print(json_string)

{"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 1], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_input"}}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_re

In [28]:
# recreate a model from json 
from tensorflow.keras.models import model_from_json
model_architecture = model_from_json(json_string)
# can do same with yaml 

In [29]:
# save weights of model 
model.save_weights('models/weights.h5')

In [30]:
# loading weights on an empty model architecture
model_architecture.load_weights('models/weights.h5')